### ISSUE TITLE
增强过滤为邮件验证码通知增加复制 按钮 

### ISSUE THREAD

**Issue by Zhuoershang** [heruoxin/FilterBox-Share-Rules#9]
对于系统短信不自动识别验证码的设备可以通过正则表达式为该通知增加 复制验证码按钮。
         同样，如果收到的邮箱通知里面包含验证码，且能够通过 正则表达式匹配到 验证码，希望可以为此类通知ye增加一个 复制验证码按钮！！！ 
         当然不限于自带的邮箱app，有些验证码邮件，微信通知内容也包含验证码，同样可以识别。

**Comment by huanchi123** [comment]
要是可以自动提取就更舒服了

**Comment by heruoxin** [comment]
大部分邮件都不是验证码邮件吧，适配邮箱的话出错率太高了
